Добавил страницы для восстановления пароля.
ToosaFinder/toosa-finder-frontend pull request #11
Opened 2020-10-16 09:19 UTC by Gregpack

Кроме этого, вынес несколько функций в utils, подредактировал стили и верстку.

2020-10-16 14:38 UTC, tigrulya-exe reviewed
Приведи сообщения коммитов к формату из вики

2020-10-18 09:17 UTC, Cyberfasolya commented on src/css/restorePassword.module.css
> +}
class form не используется в компонентах forgot_password и create_password.  У меня в регистрации тоже есть такой класс, но я его на форму навешала, и у нас сейчас у страниц верстка отличается как минимум по ширине контейнера формы всей. То есть это либо я убираю это, либо ты добавляешь в те компоненты.

2020-10-18 09:23 UTC, Cyberfasolya commented on src/open_pages/forgot_password/create_password.tsx
> +                }
Во всех аналогичных местах логика, где в зависимости от валидации введенных данных у нас подставляются разные css классы, у меня было вынесена в отдельные колбэки. Я не знаю точно, какой подход лучше, но надо как-то единообразно делать в любом случае. (аналогично там и дальше такие моменты есть в новых компонентах)

2020-10-18 09:40 UTC, Cyberfasolya requested changes

2020-10-18 09:40 UTC, Cyberfasolya commented on src/css/restorePassword.module.css
> +}
class form не используется в компонентах forgot_password и create_password. У меня в регистрации тоже есть такой класс, но я его на форму навешала, и у нас сейчас у страниц верстка отличается как минимум по ширине контейнера формы всей. То есть это либо я убираю это, либо ты добавляешь в те компоненты.

2020-10-18 09:40 UTC, Cyberfasolya commented on src/open_pages/forgot_password/create_password.tsx
> +                }
Во всех аналогичных местах логика, где в зависимости от валидации введенных данных у нас подставляются разные css классы, у меня было вынесена в отдельные колбэки. Я не знаю точно, какой подход лучше, но надо как-то единообразно делать в любом случае. (аналогично там и дальше такие моменты есть в новых компонентах)

2020-10-18 10:32 UTC, Gregpack commented on src/open_pages/forgot_password/create_password.tsx
> +                }
починил

2020-10-18 10:32 UTC, Gregpack commented on src/css/restorePassword.module.css
> +}
добавил в формы на других страницах

2020-10-18 10:49 UTC, Cyberfasolya approved these changes

2020-10-18 11:22 UTC, merged