3985 registration ui
ToosaFinder/toosa-finder-frontend pull request #5
Opened 2020-09-26 11:44 UTC by Cyberfasolya

Add registration ui

2020-09-29 03:25 UTC, Gregpack requested changes

2020-09-29 03:25 UTC, Gregpack commented on pages/registration/registration.tsx
> +                            onChange={(e) => setEmail(e.target.value)}
может, change handler-ы стоит в отдельные функции вынести? (аналогично строка 85 и 97). для обработки email, login и password можно, по идее, сделать тип credentials, для него функцию изменения и воткнуть её вместо лямбды в этих трех местах

2020-09-29 03:25 UTC, Gregpack commented on pages/registration/registration.tsx
> +                            className={getEmailClassName()}
а вот этот вот расчет валидации не замедлит ли страницу очень сильно? насколько я знаю, сопоставление с regexp это операция очень медленная, и если делать её oninput (то есть при вводе каждого символа), то это должно нещадно лагать

2020-09-29 03:25 UTC, Gregpack commented on pages/registration/registration.tsx
> +                            className={getEmailClassName()}
аналогично все остальные getClassName-ы

2020-09-29 03:25 UTC, Gregpack commented on pages/registration/registration.tsx
> +    const [passwordConfirmation, setPasswordConfirmation] = useState<string>('');
вот эти четыре стейта лучше превратить в один state<credentials>, как его обновлять - есть кусок кода в loginpage сейчас

2020-09-29 03:44 UTC, Gregpack commented on pages/registration/registration.tsx
> +                            className={getEmailClassName()}
хотя выглядеть должно, конечно красиво....

2020-09-30 15:09 UTC, Cyberfasolya commented on pages/registration/registration.tsx
> +                            className={getEmailClassName()}
Валидация введённой почты заняла 7 миллисекунд. Зрительно это вообще не заметно

![ijeffIExtTI](https://user-images.githubusercontent.com/55994246/94703727-59531a80-0369-11eb-8d3b-aa95b7ca7087.jpg)

2020-09-30 15:13 UTC, Cyberfasolya commented on pages/registration/registration.tsx
> +                            onChange={(e) => setEmail(e.target.value)}
Может быть, если одна строчка в обработчике должна быть, то не стоит это отдельно выносить?

2020-09-30 16:03 UTC, Gregpack commented on pages/registration/registration.tsx
> +                            onChange={(e) => setEmail(e.target.value)}
ну в принципе ладно

2020-09-30 16:04 UTC, Gregpack approved these changes

2020-09-30 16:31 UTC, merged